
  USE ElectronicChipTattooSchema
  GO
  CREATE LOGIN A WITH PASSWORD = '1000';
  GO
  CREATE USER A FOR LOGIN A
  GO
  GRANT SELECT, INSERT, UPDATE, DELETE ON BrainWaves TO A
  REVOKE SELECT,INSERT, UPDATE, DELETE ON BrainWaves FROM A

  GRANT SELECT, INSERT, UPDATE, DELETE ON VitalSignPeakValueMedicalHistory TO A
  REVOKE SELECT,INSERT, UPDATE, DELETE ON VitalSignPeakValueMedicalHistory FROM A

  GRANT SELECT, INSERT, UPDATE, DELETE ON Chip TO A
  REVOKE SELECT,INSERT, UPDATE, DELETE ON Chip FROM A

  GRANT SELECT, INSERT, UPDATE, DELETE ON ChipType TO A
  REVOKE SELECT,INSERT, UPDATE, DELETE ON ChipType FROM A

  GRANT SELECT, INSERT, UPDATE, DELETE ON Department TO A
  REVOKE SELECT,INSERT, UPDATE, DELETE ON Department FROM A

  GRANT SELECT, INSERT, UPDATE, DELETE ON Department_Has_Employees TO A
  REVOKE SELECT,INSERT, UPDATE, DELETE ON Department_Has_Employees FROM A

  GRANT SELECT, INSERT, UPDATE, DELETE ON Employee TO A
  REVOKE SELECT,INSERT, UPDATE, DELETE ON Employee FROM A
 
  GRANT SELECT, INSERT, UPDATE, DELETE ON Employee_Monitors_Chip TO A
  REVOKE SELECT,INSERT, UPDATE, DELETE ON Employee_Monitors_Chip FROM A

  GRANT SELECT, INSERT, UPDATE, DELETE ON Hospital TO A
  REVOKE SELECT,INSERT, UPDATE, DELETE ON Hospital FROM A

  GRANT SELECT, INSERT, UPDATE, DELETE ON  Patient TO A
  REVOKE SELECT,INSERT, UPDATE, DELETE ON  Patient FROM A

  GRANT SELECT, INSERT, UPDATE, DELETE ON  PatientType TO A
  REVOKE SELECT,INSERT, UPDATE, DELETE ON  PatientType FROM A

  GRANT SELECT, INSERT, UPDATE, DELETE ON  VitalSign TO A
  REVOKE SELECT, INSERT, UPDATE, DELETE ON  VitalSign FROM A


  



























 
  
