  USE ElectronicChipTattooSchema
  GO
  CREATE LOGIN SL WITH PASSWORD = '1014';
  GO


  CREATE USER SL FOR LOGIN SL
  GO



  GRANT SELECT, INSERT, UPDATE, DELETE ON BrainWaves TO SL

  REVOKE SELECT,INSERT, UPDATE, DELETE ON BrainWaves FROM SL


  GRANT SELECT, INSERT, UPDATE, DELETE ON VitalSignPeakValueMedicalHistory TO SL

  REVOKE SELECT,INSERT, UPDATE, DELETE ON VitalSignPeakValueMedicalHistory FROM SL


  GRANT SELECT, INSERT, UPDATE, DELETE ON Chip TO SL

  REVOKE SELECT,INSERT, UPDATE, DELETE ON Chip FROM SL



  GRANT SELECT, INSERT, UPDATE, DELETE ON ChipType TO SL

  REVOKE SELECT,INSERT, UPDATE, DELETE ON ChipType FROM SL


  
  GRANT SELECT, INSERT, UPDATE, DELETE ON Department TO SL

  REVOKE SELECT, INSERT, UPDATE, DELETE ON Department FROM SL


  GRANT SELECT, INSERT, UPDATE, DELETE ON Department_Has_Employees TO SL

  REVOKE SELECT,INSERT, UPDATE, DELETE ON Department_Has_Employees FROM SL



  GRANT SELECT, INSERT, UPDATE, DELETE ON Employee TO SL

  REVOKE SELECT,INSERT, UPDATE, DELETE ON Employee FROM SL



  GRANT SELECT, INSERT, UPDATE, DELETE ON Employee_Monitors_Chip TO SL

  REVOKE SELECT,INSERT, UPDATE, DELETE ON Employee_Monitors_Chip FROM SL



  GRANT SELECT, INSERT, UPDATE, DELETE ON Hospital TO SL

  REVOKE SELECT,INSERT, UPDATE, DELETE ON Hospital FROM SL


  GRANT SELECT, INSERT, UPDATE, DELETE ON  Patient TO SL

  REVOKE SELECT,INSERT, UPDATE, DELETE ON  Patient FROM SL


    
  GRANT SELECT, INSERT, UPDATE, DELETE ON  PatientType TO SL

  REVOKE SELECT,INSERT, UPDATE, DELETE ON  PatientType FROM SL



  GRANT SELECT, INSERT, UPDATE, DELETE ON  VitalSign TO SL

  REVOKE SELECT,INSERT, UPDATE, DELETE ON  VitalSign FROM SL



























 
  
