
  
  USE ElectronicChipTattooSchema
  GO
  CREATE LOGIN M WITH PASSWORD = '1003';
  GO

  
  CREATE USER M FOR LOGIN M
  GO


 
  GRANT SELECT, INSERT, UPDATE, DELETE ON BrainWaves TO M

  REVOKE SELECT,INSERT, UPDATE, DELETE ON BrainWaves FROM M


 
  GRANT SELECT, INSERT, UPDATE, DELETE ON VitalSignPeakValueMedicalHistory TO M

  REVOKE SELECT,INSERT, UPDATE, DELETE ON VitalSignPeakValueMedicalHistory FROM M

 
  GRANT SELECT, INSERT, UPDATE, DELETE ON Chip TO M

  REVOKE SELECT,INSERT, UPDATE, DELETE ON Chip FROM M


 
  GRANT SELECT, INSERT, UPDATE, DELETE ON ChipType TO M

  REVOKE SELECT,INSERT, UPDATE, DELETE ON ChipType FROM M


 
  GRANT SELECT, INSERT, UPDATE, DELETE ON Department TO M

  REVOKE SELECT,INSERT, UPDATE, DELETE ON Department FROM M


 
  GRANT SELECT, INSERT, UPDATE, DELETE ON Department_Has_Employees TO M

  REVOKE SELECT,INSERT, UPDATE, DELETE ON Department_Has_Employees FROM M



  
 
  GRANT SELECT, INSERT, UPDATE, DELETE ON Employee TO M

  REVOKE SELECT,INSERT, UPDATE, DELETE ON Employee FROM M


    
 
  GRANT SELECT, INSERT, UPDATE, DELETE ON Employee_Monitors_Chip TO M

  REVOKE SELECT,INSERT, UPDATE, DELETE ON Employee_Monitors_Chip FROM M



  
  GRANT SELECT, INSERT, UPDATE, DELETE ON Hospital TO M

  REVOKE SELECT,INSERT, UPDATE, DELETE ON Hospital FROM M


  GRANT SELECT, INSERT, UPDATE, DELETE ON  Patient TO M

  REVOKE SELECT,INSERT, UPDATE, DELETE ON  Patient FROM M


    
 
  GRANT SELECT, INSERT, UPDATE, DELETE ON  PatientType TO M

  REVOKE SELECT,INSERT, UPDATE, DELETE ON  PatientType FROM M



  
  GRANT SELECT, INSERT, UPDATE, DELETE ON  VitalSign TO M

  REVOKE SELECT,INSERT, UPDATE, DELETE ON  VitalSign FROM M


  


















 
  
