USE ElectronicChipTattooSchema
GO

REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_AA FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_JC FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_LH FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_MM FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_OK FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_SL FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_ZG FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_AR FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_AW FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_BB FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_MT FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_NT FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_QB FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_SL FROM A;


REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_AA FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_JC FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_LH FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_MM FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_OK FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_SL FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_ZG FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_AR FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_AW FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_BB FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_MT FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_NT FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_QB FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_SL FROM B;




REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_AA FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_JC FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_LH FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_MM FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_OK FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_SL FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_ZG FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_AR FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_AW FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_BB FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_MT FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_NT FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_QB FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_SL FROM M;




REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_AA FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_JC FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_LH FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_MM FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_OK FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_SL FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON Doctor_ZG FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_AR FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_AW FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_BB FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_MT FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_NT FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_QB FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON NURSE_SL FROM SL;


REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSAkanshaVARMA  FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSHinaBhutto  FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSMallikaPATNICK  FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSPriyaBilal  FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSRohitKumar  FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSSaurabhChandela  FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSSiddhiShree  FROM SL;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSVarunMALIK  FROM SL;




REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSAkanshaVARMA  FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSHinaBhutto  FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSMallikaPATNICK  FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSPriyaBilal  FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSRohitKumar  FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSSaurabhChandela  FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSSiddhiShree  FROM M;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSVarunMALIK  FROM M;


REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSAkanshaVARMA  FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSHinaBhutto  FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSMallikaPATNICK  FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSPriyaBilal  FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSRohitKumar  FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSSaurabhChandela  FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSSiddhiShree  FROM A;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSVarunMALIK  FROM A;



REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSAkanshaVARMA  FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSHinaBhutto  FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSMallikaPATNICK  FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSPriyaBilal  FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSRohitKumar  FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSSaurabhChandela  FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSSiddhiShree  FROM B;
REVOKE  SELECT, INSERT, UPDATE, DELETE ON patient_VSVarunMALIK  FROM B;


GRANT SELECT ON patient_VSAkanshaVARMA TO A;
GRANT SELECT ON patient_VSSiddhiShree TO A;

GRANT SELECT ON patient_VSAkanshaVARMA TO B;
GRANT SELECT ON patient_VSSiddhiShree TO B;

GRANT SELECT ON patient_VSAkanshaVARMA TO M;
GRANT SELECT ON patient_VSPriyaBilal TO M;

GRANT SELECT ON patient_VSMallikaPATNICK TO SL;
GRANT SELECT ON patient_VSSaurabhChandela TO SL;
GRANT SELECT ON patient_VSRohitKumar TO SL;









