USE SmartManufacturing
GO
CREATE LOGIN userLogin WITH PASSWORD = 'user';
GO
CREATE USER userLogin FOR LOGIN userLogin
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON DataFromSensor TO userLogin
REVOKE INSERT, UPDATE, DELETE ON DataFromSensor FROM userLogin

GRANT SELECT, INSERT, UPDATE, DELETE ON Department TO userLogin
REVOKE INSERT, UPDATE, DELETE ON Department FROM userLogin

GRANT SELECT, INSERT, UPDATE, DELETE ON DepartmentAcquiresDataFromSensor TO userLogin
REVOKE INSERT, UPDATE, DELETE ON DepartmentAcquiresDataFromSensor FROM userLogin

GRANT SELECT, INSERT, UPDATE, DELETE ON Drug TO userLogin
REVOKE INSERT, UPDATE, DELETE ON Drug FROM userLogin

GRANT SELECT, INSERT, UPDATE, DELETE ON Factory TO userLogin
REVOKE INSERT, UPDATE, DELETE ON Factory FROM userLogin

GRANT SELECT, INSERT, UPDATE, DELETE ON machineProducesDrugs TO userLogin
REVOKE INSERT, UPDATE, DELETE ON machineProducesDrugs FROM userLogin

GRANT SELECT, INSERT, UPDATE, DELETE ON machinery TO userLogin
REVOKE INSERT, UPDATE, DELETE ON machinery FROM userLogin

GRANT SELECT, INSERT, UPDATE, DELETE ON sensor TO userLogin
REVOKE INSERT, UPDATE, DELETE ON sensor FROM userLogin

GRANT SELECT, INSERT, UPDATE, DELETE ON warehouse TO userLogin
REVOKE INSERT, UPDATE, DELETE ON warehouse FROM userLogin

