USE SmartManufacturing
GO
CREATE LOGIN developer WITH PASSWORD = 'developer';
GO
CREATE USER developer FOR LOGIN developer
GO
GRANT ALTER ON SCHEMA::dbo TO developer
GRANT CREATE TABLE TO Developer
GRANT CREATE PROCEDURE TO developer
GRANT CREATE VIEW TO developer

GRANT SELECT, INSERT, UPDATE, ALTER, REFERENCES,DELETE ON DataFromSensor TO Developer
REVOKE INSERT, UPDATE, DELETE ON DataFromSensor FROM Developer

GRANT SELECT, INSERT, UPDATE, ALTER,REFERENCES,DELETE ON Department TO Developer
REVOKE INSERT,UPDATE, DELETE ON Department FROM Developer

GRANT SELECT, INSERT, UPDATE,ALTER ,REFERENCES,DELETE ON DepartmentAcquiresDataFromSensor TO Developer
REVOKE INSERT, UPDATE,DELETE ON DepartmentAcquiresDataFromSensor FROM Developer

GRANT SELECT, INSERT, UPDATE, ALTER,REFERENCES,DELETE ON Drug TO Developer
REVOKE INSERT,UPDATE, DELETE ON Drug FROM Developer

GRANT SELECT, INSERT, UPDATE, ALTER,REFERENCES,DELETE ON Factory TO Developer
REVOKE INSERT,UPDATE, DELETE ON Factory FROM Developer

GRANT SELECT, INSERT, UPDATE, ALTER,REFERENCES,DELETE ON machineProducesDrugs TO Developer
REVOKE INSERT,UPDATE, DELETE ON machineProducesDrugs FROM Developer

GRANT SELECT, INSERT, UPDATE, ALTER,REFERENCES,DELETE ON machinery TO Developer
REVOKE UPDATE, DELETE ON machinery FROM Developer

GRANT SELECT, INSERT, UPDATE, ALTER,REFERENCES,DELETE ON sensor TO Developer
REVOKE INSERT,UPDATE, DELETE ON sensor FROM Developer

GRANT SELECT, INSERT, UPDATE, ALTER,REFERENCES,DELETE ON warehouse TO Developer
REVOKE INSERT,UPDATE, DELETE ON warehouse FROM Developer